apiVersion: v1
kind: Secret
metadata:
  name: transaction-secrets
  labels:
    app: transaction-service
type: Opaque
data:
  # Credenciales codificadas en base64
  DB_HOST: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_DATABASE: dHJhbnNhY3Rpb25fZGI=

